# Generated by Django 5.0 on 2023-12-17 17:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="videos",
            options={"verbose_name": "Videos", "verbose_name_plural": "video"},
        ),
        migrations.AlterField(
            model_name="videos",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime.now, verbose_name="Request time"
            ),
        ),
    ]
